"""corrections reason and direction columns

Revision ID: 0052f47316b6
Revises: 4df327bd2500
Create Date: 2026-09-18 16:53:34.370627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0052f47316b6'
down_revision: Union[str, Sequence[str], None] = '4df327bd2500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corrections', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('corrections', sa.Column('direction', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corrections', 'direction')
    op.drop_column('corrections', 'reason')
    # ### end Alembic commands ###
