"""corrections change_type column

Revision ID: 4df327bd2500
Revises: c040cac64603
Create Date: 2026-09-18 15:34:17.841346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df327bd2500'
down_revision: Union[str, Sequence[str], None] = 'c040cac64603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corrections', sa.Column('change_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corrections', 'change_type')
    # ### end Alembic commands ###
