"""soft delete documents: partial unique index on active uploads

Revision ID: 68200034e459
Revises: 2f97e8825fdc
Create Date: 2026-09-18 18:21:58.907909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68200034e459'
down_revision: Union[str, Sequence[str], None] = '2f97e8825fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_document_claim_sha256'), 'documents', type_='unique')
    op.create_index('uq_document_claim_sha256_active', 'documents', ['claim_id', 'file_sha256'], unique=True, postgresql_where=sa.text("status != 'removed'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_document_claim_sha256_active', table_name='documents', postgresql_where=sa.text("status != 'removed'"))
    op.create_unique_constraint(op.f('uq_document_claim_sha256'), 'documents', ['claim_id', 'file_sha256'])
    # ### end Alembic commands ###
