"""employee grade and base city columns

Revision ID: 7914484842ae
Revises: 68200034e459
Create Date: 2026-09-18 20:08:22.443008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7914484842ae'
down_revision: Union[str, Sequence[str], None] = '68200034e459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('grade', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('base_city', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'base_city')
    op.drop_column('employees', 'grade')
    # ### end Alembic commands ###
