"""extraction category columns

Revision ID: 9715e7d323b3
Revises: 7914484842ae
Create Date: 2026-09-18 20:23:36.540336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9715e7d323b3'
down_revision: Union[str, Sequence[str], None] = '7914484842ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractions', sa.Column('category', sa.Text(), nullable=True))
    op.add_column('extractions', sa.Column('category_confidence', sa.Float(), nullable=True))
    op.add_column('extractions', sa.Column('category_method', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extractions', 'category_method')
    op.drop_column('extractions', 'category_confidence')
    op.drop_column('extractions', 'category')
    # ### end Alembic commands ###
