"""extraction currency column, claim currency nullable

Revision ID: c040cac64603
Revises: e7f4eb4c021a
Create Date: 2026-09-18 15:10:13.320198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c040cac64603'
down_revision: Union[str, Sequence[str], None] = 'e7f4eb4c021a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'currency',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('extractions', sa.Column('currency', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extractions', 'currency')
    op.alter_column('claims', 'currency',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
